# docker-compose.override.yml
services:
  back:
    image: maven:3.9.9-eclipse-temurin-21-jammy
    working_dir: /app
    command: mvn -B spring-boot:run        
    volumes:
      - ./jang:/app
      - ~/.m2:/root/.m2
    ports: ["8080:8080"]
    depends_on:
      mysql:
        condition: service_healthy

  front:
    image: node:18-alpine            
    build: !reset null               # ← supprime le build hérité
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare npm@10.7.0 --activate && npm ci && npm start -- --host 0.0.0.0 --port 4200 --poll=5000"
    volumes:
      - ./jang-front:/app
      - /app/node_modules
      - /app/.angular/cache
    ports: ["4201:4200"]
    depends_on:
      - back
